### ISSUE TITLE
"Out Of Index" Exception occurred while shrink sheet row and col

### ISSUE THREAD

**Issue by truthtracer** [unvell/ReoGrid#104]
redo this issue steps :

1.  set sheet  row, col and select one cell by click (pos is X1, Y1)
2.  reset the sheet by smaller row, col

if X1 or Y1 not in range of row col of step 2, then exception will happen.

> ************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at unvell.ReoGrid.Views.CellsViewport.GetScaledAndClippedRangeRect(IViewport view, CellPosition startPos, CellPosition endPos, Single borderWidth) in L:\inc_bak\ReoGrid\ReoGrid\Views\CellsViewport.cs:line 499
   at unvell.ReoGrid.Views.CellsViewport.DrawSelection(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\CellsViewport.cs:line 978
   at unvell.ReoGrid.Views.CellsViewport.DrawView(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\CellsViewport.cs:line 96
   at unvell.ReoGrid.Views.Viewport.Draw(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 448
   at unvell.ReoGrid.Views.View.DrawChildren(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 239
   at unvell.ReoGrid.Views.Viewport.DrawView(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 476
   at unvell.ReoGrid.Views.Viewport.Draw(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 448
   at unvell.ReoGrid.Views.View.DrawChildren(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 239
   at unvell.ReoGrid.Views.View.Draw(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 227
   at unvell.ReoGrid.Views.ViewportController.Draw(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\Viewport.cs:line 673
   at unvell.ReoGrid.Views.NormalViewportController.Draw(CellDrawingContext dc) in L:\inc_bak\ReoGrid\ReoGrid\Views\NormalViewportController.cs:line 1417
   at unvell.ReoGrid.ReoGridControl.OnPaint(PaintEventArgs e) in L:\inc_bak\ReoGrid\ReoGrid\WinForm\WinFormControl.cs:line 1393
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at unvell.ReoGrid.ReoGridControl.WndProc(Message& m) in L:\inc_bak\ReoGrid\ReoGrid\WinForm\WinFormControl.cs:line 1334
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I fixed it temporarily by SelectRows(0, 1) before shrinking the sheet.

**Comment by jingwood** [comment]
Thanks, seems there should move the selection after shrinking to a smaller sheet.

**Comment by jingjiajie** [comment]
Hello @jingwood ,I had the same problem and I just posted an issue. Could you fix this bug recently? Because we are using the ReoGridControl with our Enterprise Business and the client is urging us to solve this crash problem as soon as possible. I'm so appriciated to you.

**Comment by RedHatUzb** [comment]
Hello @jingwood . Could you fixed this bug!!!

**Comment by liusaiweng** [comment]
i have this bug for a long time.....   
在 System.ThrowHelper.ThrowArgumentOutOfRangeException()
   在 unvell.ReoGrid.Views.CellsViewport.<>c__DisplayClass17_0.<GetRowByPoint>b__0(Int32 i)
   在 unvell.ReoGrid.Data.ArrayHelper.QuickFind(Int32 split, Int32 start, Int32 end, Func`2 compare)
   在 unvell.ReoGrid.Views.CellsViewport.GetRowByPoint(IViewport view, Single y)
   在 unvell.ReoGrid.Views.CellsViewport.GetPosByPoint(IViewport view, Point p)
   在 unvell.ReoGrid.Views.CellsViewport.OnMouseMove(Point location, MouseButtons buttons)
   在 unvell.ReoGrid.Views.ViewportController.OnMouseMove(Point location, MouseButtons buttons)
   在 unvell.ReoGrid.ReoGridControl.OnWorksheetMouseMove(PointF location, MouseButtons buttons)
   在 unvell.ReoGrid.ReoGridControl.OnMouseMove(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseMove(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 unvell.ReoGrid.ReoGridControl.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jingwood** [comment]
I think this problem has been fixed in the latest code. I have tested the steps and no problems were found.
If anyone has this problem please let me know. Thanks!
