### ISSUE TITLE
Exception while Saving to Excel2007 format

### ISSUE THREAD

**Issue by BrianShankland** [unvell/ReoGrid#143]
Hello, 
Been a while since contacted you on your initial forum, but today I got a new error.
I'm getting an internal exception raised from the ExcelWriter:

   at unvell.ReoGrid.IO.OpenXML.ExcelWriter.<>c__DisplayClass12_0.<AddSharedString>b__0(SharedStringItem s)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at System.Collections.Generic.List`1.FindIndex(Predicate`1 match)
   at unvell.ReoGrid.IO.OpenXML.ExcelWriter.AddSharedString(Document doc, String str)
   at unvell.ReoGrid.IO.OpenXML.ExcelWriter.WriteWorksheet(Document doc, Worksheet rgSheet)
   at unvell.ReoGrid.IO.OpenXML.ExcelWriter.WriteStream(IWorkbook rgWorkbook, Stream stream)
   at unvell.ReoGrid.IO.ExcelFileFormatProvider.Save(IWorkbook workbook, Stream stream, Encoding encoding, Object arg)
   at unvell.ReoGrid.Workbook.Save(Stream stream, FileFormat fileFormat, Encoding encoding)
   at unvell.ReoGrid.Workbook.Save(String path, FileFormat fileFormat, Encoding encoding)
   at unvell.ReoGrid.ReoGridControl.Save(String path, FileFormat fileFormat, Encoding encoding)
   at unvell.ReoGrid.ReoGridControl.Save(String path, FileFormat fileFormat)

To avoid any issues that it was some attribute on the control that I was changing I simply called the .Load then the .Save methods and it fails in the same manner.

Likely something specific to this file as I can still sue with other files that I've tested with previously.

Failing File:
[FailingSheet.xlsx](https://github.com/unvell/ReoGrid/files/2188753/FailingSheet.xlsx)

Cant see anything unusual in sheet but if there is please let me know and I can remove. 
If you need any further testing or debug info am here and happy to help.

**Comment by jingwood** [comment]
I have done some test with your Excel file and no errors happened. Can you try again from the latest source code?

**Comment by BrianShankland** [comment]
Will do so tomorrow for both #143 and #145.

 

From NuGet package Manager I have V2.1.0 installed which it claims is the latest stable version.

Is there a later one I can get from elsewhere?

 

 

regards

 

_________________________________________________­_

Brian Shankland
Icon Research Ltd
3 Raw Holdings | East Calder | West Lothian | EH53 0HY | UK
T: +44 1506 885000 Ext 226
F: +44 1506 885501
 <http://www.iconresearch.co.uk/> www.iconresearch.co.uk

**Comment by BrianShankland** [comment]
Its been a while, but I eventually got time to revisit our projects problem.
I downloaded the release source code from GitHub and even though its version is the same as the one from the NuGet project manager, if I build from source the problem is  resolved.

So I'm not sure if the version held in NuGet is consistent to that held in GitHub ?
