### ISSUE TITLE
System.IndexOutOfRangeException in unvell.ReoGridEditor 2.0.1.0

### ISSUE THREAD

**Issue by Gnuelmpf** [unvell/ReoGrid#176]
Edit => Selection => Selection Mode =>None

If you try to enter text then you will get this error.
Have a sunny day
:)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at unvell.ReoGrid.Data.Index4DArray`1.get_Item(Int32 row, Int32 col)
   at unvell.ReoGrid.Worksheet.IsValidCell(Int32 row, Int32 col)
   at unvell.ReoGrid.Worksheet.StartEdit(Int32 row, Int32 col, String newText)
   at unvell.ReoGrid.Worksheet.StartEdit(String newText)
   at unvell.ReoGrid.ReoGridControl.ProcessDialogChar(Char charCode)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by jingwood** [comment]
Thanks! Fixed.
