### ISSUE TITLE
Error if inserting a new worksheet

### ISSUE THREAD

**Issue by Gnuelmpf** [unvell/ReoGrid#189]
Hi there ...
I always get an error if i try to insert a new worksheet using the integrated SheetTabContextMenuStrip. 
Renaming & deleting ar working fine.

![image](https://user-images.githubusercontent.com/43831414/47714787-1dbfeb00-dc3e-11e8-8692-5c3934d32861.png)

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at unvell.ReoGrid.Views.LeadHeaderView.Draw(CellDrawingContext dc)
   at unvell.ReoGrid.Views.View.DrawChildren(CellDrawingContext dc)
   at unvell.ReoGrid.Views.View.Draw(CellDrawingContext dc)
   at unvell.ReoGrid.Views.ViewportController.Draw(CellDrawingContext dc)
   at unvell.ReoGrid.Views.NormalViewportController.Draw(CellDrawingContext dc)
   at unvell.ReoGrid.ReoGridControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at unvell.ReoGrid.ReoGridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jingwood** [comment]
There should be some specially reasons of this problem, but it's too hard to find out without your environment, so try provide more information if you can. 

e.g. 
- actions before the problem happen
- or some pieces of code that reappear it stably

will be greatly helpful, thanks.

**Comment by Gnuelmpf** [comment]
I can try to reduce the project & keeping the error.
Can i send it to you ?
If yes where to send it ?
I can't publish it here, because of copyright issues by the university.
Thx & have a sunny weekend ...
:)

**Comment by Gnuelmpf** [comment]
OK,
I think, I have extracted where to have a closer look at.
The step which is finishing the start-sub will cause this error.

![image](https://user-images.githubusercontent.com/43831414/48952424-6b302f00-ef42-11e8-9fba-364a2a1df715.png)

**Comment by jingwood** [comment]
Thanks! This is helpful.

I can confirm this bug now, the problem is that some colors are not set in `ControlAppearanceStyle` object but ReoGrid need them, like `ControlAppearanceColors.LeadHeadNormal`.

I will consider to change this interface in order to avoid produce the problem like this, before that you can change this code
```charp
Dim rgcs as new ControlAppearanceStyle
```
to
```csharp
Dim rgcs = ControlAppearanceStyle.CreateDefaultControlStyle
```
to avoid the problem temporarily.

btw. you can use GitHub markdown syntax to paste code onto here rather than a png image, see https://guides.github.com/features/mastering-markdown/

**Comment by Gnuelmpf** [comment]
Thx,
this works fine.
You are right with the code.
I'll do it in future.
But i love all this colors.
:))
