### ISSUE TITLE
Error while loading Excel

### ISSUE THREAD

**Issue by pradip3981** [unvell/ReoGrid#53]
It seems very simple code but gives the error like attached. Please help.
![image](https://user-images.githubusercontent.com/32158570/30684866-81faa2f6-9ed0-11e7-88f5-1f9438adb082.png)

**Comment by Furgia** [comment]
I had the same problem.
At the moment I solved by opening in advance the xlsx file in xml format.
There were some cells "string"
<Cell> <ss:Data ss:Type="String" xmlns="http://www.w3.org/TR/REC-html40"> MYSTRING </ss:Data>  </Cell>
By removing the xmls reference and saving file xlsx the problem was resolved (I did not understand why)

**Comment by jingwood** [comment]
An Excel sheet which contains multiple line formatted text may cause the exception `NullReferenceException` happen. The latest source contains the fix of this, you can try from the source code.

**Comment by jingwood** [comment]
81d094b73bd32c0e77ee98a8aba91ef6b683e445 fixes this.

**Comment by RahulKumarParihar** [comment]
I am using grd.Load("Path", FileFormat.Excel2007, Encoding.UTF8) where grd is ReoGridControl.
I am still getting above _NullReferenceException_.
Here is the stack trace
   at unvell.ReoGrid.IO.OpenXML.ExcelReader.AddRunIntoRichText(Document doc, RichText rt, Run r)
   at unvell.ReoGrid.IO.OpenXML.ExcelReader.CreateRichTextFromRuns(Document doc, IEnumerable`1 paragraphs)
   at unvell.ReoGrid.IO.OpenXML.ExcelReader.LoadWorksheet(IWorkbook rgWorkbook, Document doc, WorkbookSheet sheetIndex)
   at unvell.ReoGrid.IO.OpenXML.ExcelReader.ReadStream(IWorkbook rgWorkbook, Stream stream)
   at unvell.ReoGrid.Workbook.Load(Stream stream, FileFormat fileFormat, Encoding encoding)
   at unvell.ReoGrid.Workbook.Load(String path, FileFormat fileFormat, Encoding encoding)
   at Excel.LoadDataFromExcel(ReoGridControl grd, String filePath) in d:\ExcelLoadingTool\Loading.cs:line 229
